# Generated by Django 5.2.6 on 2025-10-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado')], default='aprobado', max_length=10),
        ),
    ]
