# Generated by Django 5.2.6 on 2025-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw2', '0004_mundial_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
