# Generated by Django 5.2.6 on 2025-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw2', '0006_add_soft_delete_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mundial',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mundial',
            name='multimedia',
            field=models.ManyToManyField(blank=True, through='pw2.MultimediaMundial', to='pw2.multimedia'),
        ),
    ]
